### ISSUE TITLE
Proxy nd not clear

### ISSUE THREAD

**Issue by andreybratus** [fusepoolP3/overall-architecture#9]
The Marmotta LDP implementation has the ability to automatically configure itself on the first request based on the Host header, it assumes this to be the canonical address of the instance and redirect all subsequent requests to use this hostname and port, because of this, it is important that the first request is made via the **proxy nd** using the correct public facing hostname (i.e. not using a hostname like localhost if the instance shall later be accessed from the internet).

_**proxy nd**_ is not clear to me. I don't understand what is meant: a _proxy node_, or is it neighbour discovery?

* if [Neighbour Discovery](https://en.wikipedia.org/wiki/Neighbor_Discovery_Protocol) is meant. uppercase and add to abbreviations or reference.

**Comment by retog** [comment]
nd -> and

This clearly demonstrates what bad spelling can cause :)
